services:

  backend:

    build: .

    container_name: buildmate_backend

    ports:
      - "8000:8000"

    depends_on:
      - postgres
      - redis

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/buildmate
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: ${SECRET_KEY:-secret}

    volumes:
      - .:/app

  postgres:

    image: postgres:17

    container_name: buildmate_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: buildmate

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:

    image: redis:latest

    container_name: buildmate_redis

    ports:
      - "6379:6379"

volumes:

  postgres_data: