"""add_foreign_key_indexes

Revision ID: 54ed8325582b
Revises: 726527eace3c
Create Date: 2026-06-23 12:21:27.123971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54ed8325582b'
down_revision: Union[str, Sequence[str], None] = '726527eace3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_applications_opportunity_id'), 'applications', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_index(op.f('ix_invitations_opportunity_id'), 'invitations', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_invitations_user_id'), 'invitations', ['user_id'], unique=False)
    op.create_index(op.f('ix_opportunities_project_id'), 'opportunities', ['project_id'], unique=False)
    op.create_index(op.f('ix_opportunity_skills_opportunity_id'), 'opportunity_skills', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_skills_skill_id'), 'opportunity_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_project_skills_project_id'), 'project_skills', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_skills_skill_id'), 'project_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_user_skills_skill_id'), 'user_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_skills_user_id'), table_name='user_skills')
    op.drop_index(op.f('ix_user_skills_skill_id'), table_name='user_skills')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_project_skills_skill_id'), table_name='project_skills')
    op.drop_index(op.f('ix_project_skills_project_id'), table_name='project_skills')
    op.drop_index(op.f('ix_opportunity_skills_skill_id'), table_name='opportunity_skills')
    op.drop_index(op.f('ix_opportunity_skills_opportunity_id'), table_name='opportunity_skills')
    op.drop_index(op.f('ix_opportunities_project_id'), table_name='opportunities')
    op.drop_index(op.f('ix_invitations_user_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_opportunity_id'), table_name='invitations')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_opportunity_id'), table_name='applications')
    # ### end Alembic commands ###
