"""add_db_constraints_and_cascades

Revision ID: 726527eace3c
Revises: b7e2d4f1c9a0
Create Date: 2026-06-22 21:23:31.528244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '726527eace3c'
down_revision: Union[str, Sequence[str], None] = 'b7e2d4f1c9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('applications_user_id_fkey'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_opportunity_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'opportunities', ['opportunity_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('opportunities_project_id_fkey'), 'opportunities', type_='foreignkey')
    op.create_foreign_key(None, 'opportunities', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('profiles_user_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_resources_project_id_fkey'), 'project_resources', type_='foreignkey')
    op.create_foreign_key(None, 'project_resources', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_skills_skill_id_fkey'), 'project_skills', type_='foreignkey')
    op.drop_constraint(op.f('project_skills_project_id_fkey'), 'project_skills', type_='foreignkey')
    op.create_foreign_key(None, 'project_skills', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_skills', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('projects_owner_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_skills_skill_id_fkey'), 'user_skills', type_='foreignkey')
    op.drop_constraint(op.f('user_skills_user_id_fkey'), 'user_skills', type_='foreignkey')
    op.create_foreign_key(None, 'user_skills', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_skills', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    # Custom CheckConstraints
    op.create_check_constraint(
        'check_user_activity_score',
        'users',
        'activity_score >= 0 AND activity_score <= 100'
    )
    op.create_check_constraint(
        'check_user_reliability_score',
        'users',
        'reliability_score >= 0 AND reliability_score <= 100'
    )
    op.create_check_constraint(
        'check_opportunity_seats',
        'opportunities',
        'seats > 0'
    )
    op.create_check_constraint(
        'check_opportunity_status',
        'opportunities',
        "status IN ('open', 'closed')"
    )
    op.create_check_constraint(
        'check_application_status',
        'applications',
        "status IN ('pending', 'accepted', 'rejected')"
    )
    op.create_check_constraint(
        'check_invitation_status',
        'invitations',
        "status IN ('pending', 'accepted', 'rejected')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Custom CheckConstraints removal
    op.drop_constraint('check_invitation_status', 'invitations', type_='check')
    op.drop_constraint('check_application_status', 'applications', type_='check')
    op.drop_constraint('check_opportunity_status', 'opportunities', type_='check')
    op.drop_constraint('check_opportunity_seats', 'opportunities', type_='check')
    op.drop_constraint('check_user_reliability_score', 'users', type_='check')
    op.drop_constraint('check_user_activity_score', 'users', type_='check')

    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'user_skills', type_='foreignkey')
    op.drop_constraint(None, 'user_skills', type_='foreignkey')
    op.create_foreign_key(op.f('user_skills_user_id_fkey'), 'user_skills', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_skills_skill_id_fkey'), 'user_skills', 'skills', ['skill_id'], ['id'])
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_owner_id_fkey'), 'projects', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'project_skills', type_='foreignkey')
    op.drop_constraint(None, 'project_skills', type_='foreignkey')
    op.create_foreign_key(op.f('project_skills_project_id_fkey'), 'project_skills', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('project_skills_skill_id_fkey'), 'project_skills', 'skills', ['skill_id'], ['id'])
    op.drop_constraint(None, 'project_resources', type_='foreignkey')
    op.create_foreign_key(op.f('project_resources_project_id_fkey'), 'project_resources', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_user_id_fkey'), 'profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.create_foreign_key(op.f('opportunities_project_id_fkey'), 'opportunities', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_opportunity_id_fkey'), 'applications', 'opportunities', ['opportunity_id'], ['id'])
    op.create_foreign_key(op.f('applications_user_id_fkey'), 'applications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
