"""add project resources

Revision ID: 7729356c95d9
Revises: a6bc8e88334a
Create Date: 2026-06-10 19:11:02.375150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7729356c95d9'
down_revision: Union[str, Sequence[str], None] = 'a6bc8e88334a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.alter_column('applications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('applications', 'opportunity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_application', 'applications', ['user_id', 'opportunity_id'])
    op.alter_column('opportunities', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_skills', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_skills', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_project_skill', 'project_skills', ['project_id', 'skill_id'])
    op.alter_column('projects', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_skills', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_skills', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_user_skill', 'user_skills', ['user_id', 'skill_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_skill', 'user_skills', type_='unique')
    op.alter_column('user_skills', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_skills', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_project_skill', 'project_skills', type_='unique')
    op.alter_column('project_skills', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_skills', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('opportunities', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('uq_application', 'applications', type_='unique')
    op.alter_column('applications', 'opportunity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('applications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('college', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('degree', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('github', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('linkedin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('portfolio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('availability', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###
