"""create profiles table

Revision ID: 95ef0c14614d
Revises: 033dd54554da
Create Date: 2026-06-11 22:11:02.607616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ef0c14614d'
down_revision: Union[str, Sequence[str], None] = '033dd54554da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_resources_id'), table_name='project_resources')
    op.drop_table('project_resources')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_resources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('project_resources_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('project_resources_pkey'))
    )
    op.create_index(op.f('ix_project_resources_id'), 'project_resources', ['id'], unique=False)
    # ### end Alembic commands ###
