"""add unique constraints

Revision ID: a6bc8e88334a
Revises: 58ced5351e21
Create Date: 2026-05-30 15:28:20.199943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6bc8e88334a'
down_revision: Union[str, Sequence[str], None] = '58ced5351e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
  
    
    op.create_unique_constraint('uq_application', 'applications', ['user_id', 'opportunity_id'])
   
    
    op.create_unique_constraint('uq_project_skill', 'project_skills', ['project_id', 'skill_id'])
   
    op.create_unique_constraint('uq_user_skill', 'user_skills', ['user_id', 'skill_id'])
    # ### end Alembic commands ###


def downgrade():

    op.drop_constraint(
        'uq_user_skill',
        'user_skills',
        type_='unique'
    )

    op.drop_constraint(
        'uq_project_skill',
        'project_skills',
        type_='unique'
    )

    op.drop_constraint(
        'uq_application',
        'applications',
        type_='unique'
    )
    # ### end Alembic commands ###
