"""add password field to users

Revision ID: b86ccc14de0a
Revises: 45e8c12b7b13
Create Date: 2026-05-25 10:57:39.009191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86ccc14de0a'
down_revision: Union[str, Sequence[str], None] = '45e8c12b7b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():

    op.add_column(
        'users',
        sa.Column(
            'password',
            sa.String(),
            nullable=True
        )
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
